defmodule Mix.Tasks.JobApplications.SyncBoardsToSalt do
  @moduledoc """
  Discovers active job boards and syncs them to bot_army_infra Salt pillar.

  This task:
  1. Discovers active boards using the same logic as discover_boards
  2. Generates YAML format for Salt pillar
  3. Clones bot_army_infra to a clean /tmp directory
  4. Updates the pillar file, commits, and pushes

  Usage:
    mix job_applications.sync_boards_to_salt
    mix job_applications.sync_boards_to_salt --dry-run
    mix job_applications.sync_boards_to_salt --no-commit
  """

  use Mix.Task
  require Logger

  @default_timeout_ms 5000
  @connect_timeout_ms 3000

  @impl true
  def run(args) do
    {opts, _} = OptionParser.parse!(args, switches: [
      categories: :string,
      "dry-run": :boolean,
      "no-commit": :boolean
    ])

    dry_run = Keyword.get(opts, :dry_run, false)
    commit = !Keyword.get(opts, :no_commit, false)

    companies_by_category = load_companies_from_yaml()

    categories =
      case Keyword.get(opts, :categories) do
        nil -> Map.keys(companies_by_category)
        cats -> String.split(cats, ",") |> Enum.map(&String.trim/1)
      end

    Mix.shell().info("🔍 Discovering job boards...\n")

    companies =
      categories
      |> Enum.flat_map(fn cat -> companies_by_category[cat] || [] end)

    results = discover_boards(companies)

    {ok, err} = Enum.split_with(results, fn {_name, _slug, _source, status} ->
      match?({:ok, _}, status)
    end)

    if Enum.any?(ok) do
      Mix.shell().info("✅ Found #{length(ok)} active board(s)\n")
    end

    if Enum.any?(err) do
      Mix.shell().info("⚠️  #{length(err)} boards unavailable (will skip)\n")
    end

    boards = Enum.map(ok, fn {name, slug, source, _status} -> {name, slug, source} end)
    yaml_content = generate_yaml_pillar(boards)

    if dry_run do
      Mix.shell().info("📋 DRY RUN - Would write to Salt pillar:\n")
      Mix.shell().info(yaml_content)
    else
      if commit do
        commit_changes(yaml_content, length(ok))
      else
        case find_salt_pillar_file() do
          nil ->
            Mix.shell().info("⚠️  Salt pillar not found locally. Here's the content to add manually:\n")
            Mix.shell().info(yaml_content)
          path ->
            File.write!(path, yaml_content)
            Mix.shell().info("✅ Wrote: #{path}\n")
        end
      end
    end

    :ok
  end

  defp discover_boards(companies) do
    Enum.map(companies, fn {name, slug, source} ->
      Mix.shell().info("  Checking #{name}...")
      status = check_board(source, slug)
      {name, slug, source, status}
    end)
  end

  defp check_board("greenhouse", token) do
    url = "https://boards-api.greenhouse.io/v1/boards/#{URI.encode(token)}/jobs?content=false"
    http_get_json(url)
  end

  defp check_board("lever", site) do
    url = "https://api.lever.co/v0/postings/#{URI.encode(site)}?mode=json&limit=1"
    http_get_json(url)
  end

  defp http_get_json(url) do
    with {:ok, {_, _, body}} <- http_get(url),
         {:ok, data} <- Jason.decode(body) do
      cond do
        is_list(data) -> {:ok, "has_jobs"}
        is_map(data) && is_list(data["jobs"]) -> {:ok, length(data["jobs"])}
        true -> {:error, "no_jobs"}
      end
    else
      {:error, :not_found} -> {:error, "not_found"}
      {:error, :timeout} -> {:error, "timeout"}
      {:error, reason} -> {:error, inspect(reason)}
    end
  rescue
    e -> {:error, "exception: #{inspect(e)}"}
  end

  defp http_get(url) do
    url_str = String.to_charlist(url)
    case :inets.start() do
      {:ok, _} -> :ok
      {:error, {:already_started, :inets}} -> :ok
      {:error, e} -> throw(e)
    end
    http_options = [timeout: @default_timeout_ms, connect_timeout: @connect_timeout_ms]
    options = [{:sync, true}, {:body_format, :binary}]
    case :httpc.request(:get, {url_str, []}, http_options, options) do
      {:ok, {status_line, _headers, body}} ->
        {_, status_code, _} = status_line
        if status_code == 200, do: {:ok, {status_line, [], body}}, else: {:error, status_code}
      {:error, reason} -> {:error, reason}
    end
  rescue
    e -> {:error, inspect(e)}
  end

  defp generate_yaml_pillar(boards) do
    board_list = Enum.map_join(boards, "\n", fn {name, slug, source} ->
      case source do
        "greenhouse" -> "    - source: greenhouse\n      board_token: #{slug}\n      company_name: #{name}"
        "lever" -> "    - source: lever\n      site: #{slug}\n      company_name: #{name}"
      end
    end)

    """
    # Auto-generated by: mix job_applications.sync_boards_to_salt
    # Last updated: #{DateTime.utc_now() |> DateTime.to_iso8601()}

    bot_army:
      job_applications:
        ingestion_interval_ms: 21600000  # 6 hours
        ingestion_boards:
    #{board_list}
    """
  end

  defp find_salt_pillar_file do
    paths = [
      "/Users/abby/code/bot_army_infra/salt/pillar/job_applications.sls",
      "/opt/bot_army/pillar/job_applications.sls",
      "../bot_army_infra/salt/pillar/job_applications.sls",
      "../../bot_army_infra/salt/pillar/job_applications.sls",
    ]
    Enum.find_value(paths, fn path ->
      expanded = Path.expand(path)
      if File.exists?(expanded), do: expanded
    end)
  end

  defp infra_repo_url do
    local_infra = "/Users/abby/code/bot_army_infra"
    if File.dir?(local_infra) do
      case System.cmd("git", ["remote", "get-url", "origin"], cd: local_infra) do
        {url, 0} -> {:ok, String.trim(url)}
        _ -> :error
      end
    else
      :error
    end
    |> case do
      {:ok, url} -> url
      :error -> "git@github.com:ergon-automation-labs/ergon-infra.git"
    end
  end

  defp commit_changes(yaml_content, board_count) do
    repo_url = infra_repo_url()
    tmp_dir = "/tmp/bot_army_infra_sync_#{:os.system_time(:millisecond)}"
    Mix.shell().info("📦 Cloning #{repo_url} to #{tmp_dir}...")

    clone_result = System.cmd("git", ["clone", "--quiet", repo_url, tmp_dir], [])
    case clone_result do
      {_, 0} ->
        write_and_push(tmp_dir, yaml_content, board_count)
      {err, _} ->
        Mix.shell().error("⚠️  Git clone failed: #{err}")
        Mix.shell().info("⚠️  Falling back to local write...")
        case find_salt_pillar_file() do
          nil ->
            Mix.shell().info("⚠️  No local pillar found. Here's the content:\n")
            Mix.shell().info(yaml_content)
          path ->
            File.write!(path, yaml_content)
            Mix.shell().info("✅ Wrote: #{path}")
        end
    end
    System.cmd("rm", ["-rf", tmp_dir])
  end

  defp write_and_push(tmp_dir, yaml_content, board_count) do
    pillar_path = Path.join([tmp_dir, "salt", "pillar", "job_applications.sls"])
    if File.exists?(pillar_path) do
      File.write!(pillar_path, yaml_content)
      Mix.shell().info("✅ Updated: #{pillar_path}")
      msg = """
      Update ingestion_boards: #{board_count} active job boards

      Auto-discovered and synced via mix job_applications.sync_boards_to_salt
      Includes boards from Greenhouse and Lever APIs
      """
      case System.cmd("git", ["add", "salt/pillar/job_applications.sls"], cd: tmp_dir) do
        {_, 0} ->
          case System.cmd("git", ["commit", "-m", msg], cd: tmp_dir) do
            {_, 0} ->
              case System.cmd("git", ["push", "origin", "main"], cd: tmp_dir) do
                {_, 0} -> Mix.shell().info("✅ Committed and pushed to bot_army_infra\n")
                {err, _} ->
                  Mix.shell().error("⚠️  Push failed: #{err}")
                  Mix.shell().info("   Commit exists in #{tmp_dir} — push manually:")
                  Mix.shell().info("   cd #{tmp_dir} && git push origin main")
              end
            {err, _} -> Mix.shell().error("⚠️  Commit failed: #{err}")
          end
        {err, _} -> Mix.shell().error("⚠️  Git add failed: #{err}")
      end
    else
      Mix.shell().error("⚠️  Pillar file not found in clone at #{pillar_path}")
      Mix.shell().info(yaml_content)
    end
  end

  defp load_companies_from_yaml do
    yaml_paths = [
      "companies.yaml",
      "lib/mix/tasks/companies.yaml",
      File.cwd!() <> "/companies.yaml"
    ]
    yaml_file = Enum.find(yaml_paths, &File.exists?/1)
    if yaml_file do
      case File.read(yaml_file) do
        {:ok, content} -> parse_companies_yaml(content)
        {:error, reason} ->
          Mix.shell().error("⚠️  Failed to read companies.yaml: #{inspect(reason)}")
          %{}
      end
    else
      Mix.shell().error("⚠️  companies.yaml not found in common locations")
      %{}
    end
  end

  defp parse_companies_yaml(yaml_content) do
    yaml_content
    |> String.split("\n")
    |> Enum.reduce({%{}, nil}, fn line, {categories, current_category} ->
      trimmed = String.trim(line)
      cond do
        String.match?(trimmed, ~r/^[a-z_]+:\s*$/) ->
          {Map.put(categories, String.trim_trailing(trimmed, ":"), []), String.trim_trailing(trimmed, ":")}
        String.match?(line, ~r/^\s+\w/) and not String.starts_with?(trimmed, "#") ->
          if current_category, do: parse_company_line(trimmed, categories, current_category), else: {categories, current_category}
        true -> {categories, current_category}
      end
    end)
    |> elem(0)
  end

  defp parse_company_line(line, categories, current_category) do
    case String.split(line, ":", parts: 2) do
      [name, rest] ->
        name = String.trim(name)
        rest = String.trim(rest)
        with {:ok, slug} <- extract_field(rest, "slug"),
             {:ok, platform} <- extract_field(rest, "platform") do
          updated = categories[current_category] ++ [{name, slug, platform}]
          {Map.put(categories, current_category, updated), current_category}
        else
          :error -> {categories, current_category}
        end
      _ -> {categories, current_category}
    end
  end

  defp extract_field(str, field_name) do
    case Regex.run(~r/#{field_name}:\s*(\w+)/, str, capture: :all_but_first) do
      [value] -> {:ok, value}
      _ -> :error
    end
  end
end
